import { HeaderLayout } from "./components";
import "./globals.css";

export const metadata = {
  title: "Podcast app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        {children}
      </body>
    </html>
  );
}
