import podcastService from "../services/podcasts.service";
import { PodcastsProvider } from "./_providers/podcasts";
import { HeaderLayout } from "./components";
import "./globals.css";

export const metadata = {
  title: "Podcast app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const podcasts = await podcastService.listPodcasts({
    limit: 100,
    genre: 1310,
  });

  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        <PodcastsProvider podcasts={podcasts}>{children}</PodcastsProvider>
      </body>
    </html>
  );
}
